### ISSUE TITLE
Data Preparation for COCO Issue

### ISSUE THREAD

**Issue by greeneggsandyaml** [facebookresearch/Detic#9]
Hello, I am trying to prepare the data for zero-shot COCO.

When I run `get_cc_tags.py`, the code breaks because `'categories'` is not in `cc_data`, here: https://github.com/facebookresearch/Detic/blob/main/tools/get_cc_tags.py#L135

If I try to use `--cat_path`, the code again breaks because `'categories'` is not in `cc_data`, here: 
https://github.com/facebookresearch/Detic/blob/main/tools/get_cc_tags.py#L128

Could you help me out with this?

Thanks so much!

**Comment by xingyizhou** [comment]
Hi,
  Thank you for your interest. What are your commands that give the error? `categories` should have been added to the data [here](https://github.com/facebookresearch/Detic/blob/main/tools/get_coco_zeroshot_oriorder.py#L15). Please make sure you have run `get_coco_zeroshot_oriorder.py` before `get_cc_tags.py`.

**Comment by greeneggsandyaml** [comment]
Hi, thanks for the quick reply. 

The README says to run:
```
python tools/get_coco_zeroshot_oriorder.py --data_path datasets/coco/zero-shot/instances_train2017_seen_2.json
python tools/get_coco_zeroshot_oriorder.py --data_path datasets/coco/zero-shot/instances_val2017_all_2.json
```

Doesn't that add them to `datasets/coco/zero-shot/instances_train2017_seen_2.json`, not `captions_train2017.json`?

**Comment by VSPW-dataset** [comment]
I met the same problem. Have you solved it ?

**Comment by xingyizhou** [comment]
Sorry for the delay. I have fixed this in the latest commit. You will need to add `--cat_path datasets/coco/annotations/instances_val2017.json`.

**Comment by greeneggsandyaml** [comment]
Thanks. I pulled and the command works now. 

I'm now trying to run a training script. For example:
```bash
python train_net.py --num-gpus 1 --config-file ./configs/Detic_OVCOCO_CLIP_R50_1x_max-size.yaml
```

Is this correct? 

When I run it, I get an error: 
```
  ...

  File "/path/to/Detic/detic/modeling/utils.py", line 9, in load_class_freq
    cat_info = json.load(open(path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
```

**Comment by xingyizhou** [comment]
Sorry for missing this. It is from

~~~
python tools/get_lvis_cat_info.py --ann datasets/coco/zero-shot/instances_train2017_seen_2_oriorder.json
~~~

**Comment by lightas** [comment]
I got the same error with @greeneggsandyaml. The file "instances_train2017_seen_2_oriorder_cat_info.json" is missing.

**Comment by greeneggsandyaml** [comment]
The response from xingyizhou solved the issue for me. It's still missing even after you ran that?

**Comment by lightas** [comment]
@xingyizhou  @greeneggsandyaml Oh, thanks, now I solved this problem.

**Comment by greeneggsandyaml** [comment]
Thank you for your help @xingyizhou. All the data is now prepared and I am able to start training. 

I now have a different problem, which is that training keeps diverging. However, since that is unrelated to this topic, I have created a new GitHub issue (#22). 

Thanks again. I am closing this issue.
